image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-api-gateway:
  stage: build
  script:
    gradle api-gateway:assemble api-gateway:testClasses

checkStyle-api-gateway:
  stage: staticAnalysis
  script:
    gradle api-gateway:checkstyleMain api-gateway:checkStyleTest
  allow_failure: true


PMD-api-gateway:
  stage: staticAnalysis
  script:
    gradle api-gateway:pmdMain
  allow_failure: true
  