image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-message-microservice:
  stage: build
  script:
    gradle message-microservice:assemble message-microservice:testClasses

checkStyle-message-microservice:
  stage: staticAnalysis
  script:
    gradle message-microservice:checkstyleMain message-microservice:checkStyleTest
  allow_failure: true


PMD-message-microservice:
  stage: staticAnalysis
  script:
    gradle message-microservice:pmdMain
  allow_failure: true

test-message-microservice:
  stage: test
  script:
    - gradle message-microservice:test message-microservice:jacocoTestReport
    - cat message-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
